## YAML Template.
spring:
#    jpa:
#        ddl-auto: update
#        show-sql: true
#    datasource:
#        url: jdbc:mysql://localhost:3306/springboot54
#        username: root
#        password: intello
    profiles:
        active: native
    application:
        name: boot
    cloud:
        config:
            uri: http://localhost:8888
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:mysql://localhost:3306/springboot54
#spring.datasource.username=root
#spring.datasource.password=intello
#spring.cloud.config.uri=http://localhost:8888